--game.disperror("This is a test error generated by Lua! Your scripting engine works! Wow, this is a very long message isn't it? I wonder how well it'll wrap if I keep going like I am right now. I heard she sells seashells by the seashore.");
--game.message("Message test!");
--game.message("Color test!", 2);

--game.settile(this.x, this.y, "~", 1);
